name: stistools
channels:
  - http://ssb.stsci.edu/conda-dev
  - conda-forge
dependencies:
  - numpy>=1.5.1
  - numpydoc
  - astropy>=0.3.1
  - scipy>=0.14
  - sphinx=1.4
  - ipython
  - stsci.tools
  - d2to1
  - stsci.distutils
  - stsci.tools
  - pip:
    - stsci_rtd_theme
    - sphinx_automodapi
